//---------------------------------------------------------------------------
#ifndef HomeH
#define HomeH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <Menus.hpp>
#include <ToolWin.hpp>
#include <IBEvents.hpp>
#include <DB.hpp>
#include <DBClient.hpp>
#include <IBCustomDataSet.hpp>
#include <IBDatabase.hpp>
#include <IBQuery.hpp>
#include <Provider.hpp>
#include <DBGrids.hpp>
#include <Grids.hpp>
#include <Buttons.hpp>

#include <sysmac.h>

#include "DMApp.h"
#include "CadCliente.h"
#include "ConsCliente.h"
#include "CadMonitoramento.h"
#include "OcorrenciaAviso.h"
#include "Ocorrencia.h"
#include "CadProcedimento.h"
#include "CadFilial.h"
#include "CadUsuario.h"
#include "CadSenhas.h"
#include "CadClienteProcedimento.h"
#include "OcorrenciasAbertas.h"
#include "CadContratoBasico.h"
#include <dbcgrids.hpp>
#include "SHDocVw_OCX.h"
#include <OleCtrls.hpp>

//---------------------------------------------------------------------------
class TFHome : public TForm
{
__published:	// IDE-managed Components
    TMainMenu *MMenuHome;
    TMenuItem *MnCadastros;
    TStatusBar *SBarHome;
    TPanel *PHome;
    TMenuItem *MnFiliais;
    TMenuItem *MnUsuarios;
    TMenuItem *N3;
    TMenuItem *MnSair;
    TMenuItem *MnConfiguracao;
    TMenuItem *MnConsultas;
    TMenuItem *MnRelatorios;
    TMenuItem *MnConsClientes;
    TMenuItem *MnAjuda;
    TMenuItem *MnCadCliente;
    TMenuItem *MnCadContrato;
    TMenuItem *N1;
    TMenuItem *MnOrdemServico;
    TMenuItem *MnCadProcedimento;
    TTimer *TMRConsulta;
    TDataSource *DSEventos;
    TClientDataSet *CDSConsEventos;
    TIntegerField *CDSConsEventosCTX;
    TIntegerField *CDSConsEventosPORTACOM;
    TIntegerField *CDSConsEventosEQUIPAMENTO;
    TStringField *CDSConsEventosDESTATUS;
    TStringField *CDSConsEventosNMCLIENTE;
    TStringField *CDSConsEventosENDERECO;
    TStringField *CDSConsEventosCIDADE;
    TDateTimeField *CDSConsEventosDATAEVENTO;
    TDataSetProvider *DSPEventos;
    TIBQuery *IBQConsEventos;
    TIntegerField *IBQConsEventosCTX;
    TIntegerField *IBQConsEventosPORTACOM;
    TIntegerField *IBQConsEventosEQUIPAMENTO;
    TIBStringField *IBQConsEventosDESTATUS;
    TIBStringField *IBQConsEventosNMCLIENTE;
    TIBStringField *IBQConsEventosENDERECO;
    TIBStringField *IBQConsEventosCIDADE;
    TDateTimeField *IBQConsEventosDATAEVENTO;
    TIBTransaction *IBTConsEventos;
    TPageControl *PGCHome;
    TTabSheet *TSRegistroEventos;
    TSpeedButton *BtnConsultar;
    TGroupBox *GBData;
    TLabel *Label3;
    TLabel *Label2;
    TDateTimePicker *EdtDataFinal;
    TDateTimePicker *EdtDataInicial;
    TGroupBox *GBCliente;
    TLabel *Label6;
    TLabel *Label4;
    TLabel *Label8;
    TEdit *EdtCodCliente;
    TEdit *EdtNome;
    TEdit *EdtCodificador;
    TGroupBox *GBEstatus;
    TLabel *Label5;
    TLabel *Label9;
    TEdit *EdtStatus;
    TEdit *EdtStatusDescricao;
    TCheckBox *CkbAtualizar;
    TTimer *TMRMonitoramento;
    TIBEvents *IBEOcorrencia;
    TTabSheet *TSRegistroManutencao;
    TMenuItem *MnMonitorSerial;
    TMenuItem *MnMonitor1;
    TMenuItem *MnMonitor2;
    TMenuItem *MnMonitor3;
    TMenuItem *MnMonitor4;
    TMenuItem *MnMonitor5;
    TMenuItem *MnMonitor6;
    TMenuItem *MnMonitor7;
    TMenuItem *MnMonitor8;
    TMenuItem *MnMonitor9;
    TMenuItem *MnMonitor10;
    TMenuItem *MnMonitor11;
    TMenuItem *MnMonitor12;
    TMenuItem *MnMonitor13;
    TMenuItem *MnMonitor14;
    TMenuItem *MnMonitor15;
    TMenuItem *MnMonitor16;
    TTabSheet *TSResgistroOcorrencia;
    TGroupBox *GroupBox1;
    TLabel *Label1;
    TLabel *Label7;
    TDateTimePicker *EdtDataFinalOC;
    TDateTimePicker *EdtDataInicialOC;
    TSpeedButton *BtnConsultarOC;
    TDBGrid *DBGOcorrenciasHist;
    TDataSource *DSRelAtendimento;
    TClientDataSet *CDSRelAtendimento;
    TDataSetProvider *DSPRelAtendimento;
    TIBQuery *IBQRelAtendimento;
    TIBTransaction *IBTRelAtendimento;
    TPanel *PNLEventos;
    TDBGrid *DBGEventos;
    TSplitter *Splitter1;
    TIBTransaction *IBTOcorrenciasAbertas;
    TIBQuery *IBQOcorrenciasAbertas;
    TIntegerField *IBQOcorrenciasAbertasCDOCORRENCIA;
    TIntegerField *IBQOcorrenciasAbertasCTX;
    TIntegerField *IBQOcorrenciasAbertasPORTACOM;
    TIntegerField *IBQOcorrenciasAbertasEQUIPAMENTO;
    TIBStringField *IBQOcorrenciasAbertasSTATUS;
    TIBStringField *IBQOcorrenciasAbertasDESTATUS;
    TIBStringField *IBQOcorrenciasAbertasNMCLIENTE;
    TIBStringField *IBQOcorrenciasAbertasENDERECO;
    TIBStringField *IBQOcorrenciasAbertasBAIRRO;
    TIBStringField *IBQOcorrenciasAbertasCIDADE;
    TIntegerField *IBQOcorrenciasAbertasCDOPERADORENCERRAMENTO;
    TIntegerField *IBQOcorrenciasAbertasCDTIPOOCORRENCIA;
    TIntegerField *IBQOcorrenciasAbertasCDSUBTIPOOCORRENCIA;
    TIBStringField *IBQOcorrenciasAbertasRESUMO;
    TDataSetProvider *DSPOcorrenciasAbertas;
    TClientDataSet *CDSOcorrenciasAbertas;
    TIntegerField *CDSOcorrenciasAbertasCDOCORRENCIA;
    TIntegerField *CDSOcorrenciasAbertasCTX;
    TIntegerField *CDSOcorrenciasAbertasPORTACOM;
    TIntegerField *CDSOcorrenciasAbertasEQUIPAMENTO;
    TStringField *CDSOcorrenciasAbertasSTATUS;
    TStringField *CDSOcorrenciasAbertasDESTATUS;
    TStringField *CDSOcorrenciasAbertasNMCLIENTE;
    TStringField *CDSOcorrenciasAbertasENDERECO;
    TStringField *CDSOcorrenciasAbertasBAIRRO;
    TStringField *CDSOcorrenciasAbertasCIDADE;
    TIntegerField *CDSOcorrenciasAbertasCDOPERADORENCERRAMENTO;
    TIntegerField *CDSOcorrenciasAbertasCDTIPOOCORRENCIA;
    TIntegerField *CDSOcorrenciasAbertasCDSUBTIPOOCORRENCIA;
    TStringField *CDSOcorrenciasAbertasRESUMO;
    TDataSource *DSOcorrenciasAbertas;
    TIBStringField *IBQConsEventosSTATUS;
    TStringField *CDSConsEventosSTATUS;
    TIBTransaction *IBTConsFaltaComunicacao;
    TIBQuery *IBQConsFaltaComunicacao;
    TDataSetProvider *DSPConsFaltaComunicacao;
    TClientDataSet *CDSConsFaltaComunicacao;
    TDataSource *DSConsFaltaComunicacao;
    TIntegerField *IBQConsFaltaComunicacaoCTX;
    TIntegerField *IBQConsFaltaComunicacaoPORTACOM;
    TIntegerField *IBQConsFaltaComunicacaoTIPOCTX;
    TDateTimeField *IBQConsFaltaComunicacaoDATACONEXAO;
    TDateTimeField *IBQConsFaltaComunicacaoDATA_ULTIMOEVENTO;
    TLargeintField *IBQConsFaltaComunicacaoMINUTOS_SEM_COMUNICACAO;
    TIntegerField *CDSConsFaltaComunicacaoCTX;
    TIntegerField *CDSConsFaltaComunicacaoPORTACOM;
    TIntegerField *CDSConsFaltaComunicacaoTIPOCTX;
    TDateTimeField *CDSConsFaltaComunicacaoDATACONEXAO;
    TDateTimeField *CDSConsFaltaComunicacaoDATA_ULTIMOEVENTO;
    TLargeintField *CDSConsFaltaComunicacaoMINUTOS_SEM_COMUNICACAO;
    TIntegerField *IBQConsFaltaComunicacaoCDUSUARIO_DESATIVOU;
    TIBStringField *IBQConsFaltaComunicacaoMOTIVO_DESATIVOU;
    TIntegerField *CDSConsFaltaComunicacaoCDUSUARIO_DESATIVOU;
    TStringField *CDSConsFaltaComunicacaoMOTIVO_DESATIVOU;
    TIntegerField *IBQConsFaltaComunicacaoMONITORAMENTO_ATIVO;
    TIntegerField *CDSConsFaltaComunicacaoMONITORAMENTO_ATIVO;
    TMenuItem *MnRelAtendimento;
    TGroupBox *GroupBox2;
    TLabel *Label10;
    TLabel *Label11;
    TLabel *Label12;
    TEdit *EdtCodClienteOC;
    TEdit *EdtNomeOC;
    TEdit *EdtCodificadorOC;
    TGroupBox *GroupBox3;
    TLabel *Label13;
    TLabel *Label14;
    TEdit *EdtStatusOC;
    TEdit *EdtStatusDescricaoOC;
    TMenuItem *MnCadastrarOS;
    TMenuItem *MnConsultarOS;
    TDBGrid *DBGOcorrencias;
    TMenuItem *MnCadCodificador;
    TDateTimeField *IBQOcorrenciasAbertasDATAEVENTO;
    TIntegerField *IBQOcorrenciasAbertasCDCLIENTE;
    TDateTimeField *CDSOcorrenciasAbertasDATAEVENTO;
    TIntegerField *CDSOcorrenciasAbertasCDCLIENTE;
    TIntegerField *IBQConsEventosCDCLIENTE;
    TIntegerField *CDSConsEventosCDCLIENTE;
    TDateTimeField *IBQRelAtendimentoDATAEVENTO;
    TIntegerField *IBQRelAtendimentoCTX;
    TIntegerField *IBQRelAtendimentoPORTACOM;
    TIntegerField *IBQRelAtendimentoEQUIPAMENTO;
    TIBStringField *IBQRelAtendimentoNMCLIENTE;
    TIBStringField *IBQRelAtendimentoENDERECO;
    TIBStringField *IBQRelAtendimentoCIDADE;
    TIBStringField *IBQRelAtendimentoSTATUS;
    TIBStringField *IBQRelAtendimentoDESTATUS;
    TIBStringField *IBQRelAtendimentoLOCAL;
    TIBStringField *IBQRelAtendimentoRESUMO;
    TIBStringField *IBQRelAtendimentoOPERADORABERTURA;
    TIBStringField *IBQRelAtendimentoOPERADORENCERRAMENTO;
    TIBStringField *IBQRelAtendimentoAGENTE;
    TIBBCDField *IBQRelAtendimentoKMTOTALPERCORRIDO;
    TDateTimeField *CDSRelAtendimentoDATAEVENTO;
    TIntegerField *CDSRelAtendimentoCTX;
    TIntegerField *CDSRelAtendimentoPORTACOM;
    TIntegerField *CDSRelAtendimentoEQUIPAMENTO;
    TStringField *CDSRelAtendimentoNMCLIENTE;
    TStringField *CDSRelAtendimentoENDERECO;
    TStringField *CDSRelAtendimentoCIDADE;
    TStringField *CDSRelAtendimentoSTATUS;
    TStringField *CDSRelAtendimentoDESTATUS;
    TStringField *CDSRelAtendimentoLOCAL;
    TStringField *CDSRelAtendimentoRESUMO;
    TStringField *CDSRelAtendimentoOPERADORABERTURA;
    TStringField *CDSRelAtendimentoOPERADORENCERRAMENTO;
    TStringField *CDSRelAtendimentoAGENTE;
    TBCDField *CDSRelAtendimentoKMTOTALPERCORRIDO;
    TIntegerField *IBQRelAtendimentoCDCLIENTE;
    TIntegerField *CDSRelAtendimentoCDCLIENTE;
    TIntegerField *IBQRelAtendimentoCDOCORRENCIA;
    TIntegerField *CDSRelAtendimentoCDOCORRENCIA;
    TSpeedButton *BtnImprimirOC;
    TMenuItem *MnAtendimento;
    TMenuItem *MnAbrirOcorrencia;
    TPanel *Panel2;
    TSplitter *Splitter2;
    TDBGrid *DBGClientesManutencao;
    TDataSource *DSSetorCurto;
    TClientDataSet *CDSSetorCurto;
    TDataSetProvider *DSPSetorCurto;
    TIBQuery *IBQSetorCurto;
    TIBTransaction *IBTSetorCurto;
    TPanel *Panel1;
    TLabel *Label15;
    TIBStringField *IBQSetorCurtoNMCLIENTE;
    TIntegerField *IBQSetorCurtoEQUIPAMENTO;
    TIBStringField *IBQSetorCurtoDESUBTIPOOCORRENCIA;
    TStringField *CDSSetorCurtoNMCLIENTE;
    TIntegerField *CDSSetorCurtoEQUIPAMENTO;
    TStringField *CDSSetorCurtoDESUBTIPOOCORRENCIA;
    TIBTransaction *IBTBateriaFraca;
    TIBQuery *IBQBateriaFraca;
    TDataSetProvider *DSPBateriaFraca;
    TClientDataSet *CDSBateriaFraca;
    TStringField *StringField1;
    TIntegerField *IntegerField4;
    TStringField *StringField2;
    TDataSource *DSBateriaFraca;
    TDataSource *DSSensorIRContPreso;
    TClientDataSet *CDSSensorIRContPreso;
    TStringField *StringField3;
    TIntegerField *IntegerField6;
    TStringField *StringField4;
    TDataSetProvider *DSPSensorIRContPreso;
    TIBQuery *IBQSensorIRContPreso;
    TIBTransaction *IBTSensorIRContPreso;
    TDataSource *DSIdentifica;
    TClientDataSet *CDSIdentifica;
    TDataSetProvider *DSPIdentifica;
    TIBQuery *IBQIdentifica;
    TIBTransaction *IBTIdentifica;
    TIntegerField *CDSSensorIRContPresoTOTAL;
    TIntegerField *CDSBateriaFracaTOTAL;
    TIntegerField *IBQSetorCurtoTOTAL;
    TIntegerField *CDSSetorCurtoTOTAL;
    TIntegerField *IBQIdentificaCDCLIENTE;
    TIBStringField *IBQIdentificaNMCLIENTE;
    TIntegerField *IBQIdentificaEQUIPAMENTO;
    TIntegerField *IBQIdentificaTOTAL;
    TStringField *CDSIdentificaNMCLIENTE;
    TIntegerField *CDSIdentificaEQUIPAMENTO;
    TIntegerField *CDSIdentificaTOTAL;
    TStringField *CDSIdentificaPERCENTUAL;
    TDataSource *DSIdentificaZero;
    TClientDataSet *CDSIdentificaZero;
    TDataSetProvider *DSPIdentificaZero;
    TIBQuery *IBQIdentificaZero;
    TIBTransaction *IBTIdentificaZero;
    TIntegerField *IBQIdentificaZeroCDCLIENTE;
    TIBStringField *IBQIdentificaZeroNMCLIENTE;
    TIntegerField *IBQIdentificaZeroEQUIPAMENTO;
    TIntegerField *IBQIdentificaZeroTOTAL;
    TIntegerField *CDSIdentificaZeroCDCLIENTE;
    TStringField *CDSIdentificaZeroNMCLIENTE;
    TIntegerField *CDSIdentificaZeroEQUIPAMENTO;
    TIntegerField *CDSIdentificaZeroTOTAL;
    TStringField *CDSIdentificaZeroPERCENTUAL;
    TIBTransaction *IBTConsertoSistema;
    TIBQuery *IBQConsertoSistema;
    TDataSetProvider *DSPConsertoSistema;
    TClientDataSet *CDSConsertoSistema;
    TDataSource *DSConsertoSistema;
    TIntegerField *IBQIdentificaZeroTOTAL_ATIVA;
    TIntegerField *CDSIdentificaZeroTOTAL_ATIVA;
    TStringField *CDSIdentificaZeroOBSERVACAO;
    TPanel *Panel3;
    TPageControl *PGCOrdemServico;
    TTabSheet *TSOrdensServico;
    TDBGrid *DBGCliConsOrdensAbertas;
    TTabSheet *TSArmeDesarme;
    TIBQuery *IBQCliConsOrdemServico;
    TClientDataSet *CDSCliConsOrdemServico;
    TDataSource *DSCliConsOrdemServico;
    TDataSource *DSMasterCliConsOrdemServico;
    TIntegerField *CDSIdentificaCDCLIENTE;
    TIntegerField *IBQIdentificaZeroTOTAL_PENDENTE;
    TIntegerField *IBQIdentificaZeroTOTAL_REALIZADO;
    TIntegerField *CDSIdentificaZeroTOTAL_PENDENTE;
    TIntegerField *CDSIdentificaZeroTOTAL_REALIZADO;
    TSpeedButton *BtnConsultarManutPreventivas;
    TIBQuery *IBQCliConsArmeDesarme;
    TClientDataSet *CDSCliConsArmeDesarme;
    TDataSource *DSCliConsArmeDesarme;
    TDataSource *DSCliConsLogEvento;
    TClientDataSet *CDSCliConsLogEvento;
    TIBQuery *IBQCliConsLogEvento;
    TIBQuery *IBQCliConsOcorrencia;
    TClientDataSet *CDSCliConsOcorrencia;
    TDataSource *DSCliConsOcorrencia;
    TIntegerField *IBQSetorCurtoCDCLIENTE;
    TIntegerField *CDSSetorCurtoCDCLIENTE;
    TIntegerField *CDSBateriaFracaCDCLIENTE;
    TIntegerField *CDSSensorIRContPresoCDCLIENTE;
    TTabSheet *TSOcorrencias;
    TDBGrid *DBGCliConsOcorrencias;
    TDBGrid *DBGCliConsArmeDesarme;
    TTabSheet *TSEventos;
    TDBGrid *DBGCliConsEventos;
    TIntegerField *IBQCliConsOcorrenciaCDOCORRENCIA;
    TDateTimeField *IBQCliConsOcorrenciaDATAEVENTO;
    TIntegerField *IBQCliConsOcorrenciaCTX;
    TIntegerField *IBQCliConsOcorrenciaPORTACOM;
    TIntegerField *IBQCliConsOcorrenciaEQUIPAMENTO;
    TIntegerField *IBQCliConsOcorrenciaCDCLIENTE;
    TIBStringField *IBQCliConsOcorrenciaNMCLIENTE;
    TIBStringField *IBQCliConsOcorrenciaENDERECO;
    TIBStringField *IBQCliConsOcorrenciaCIDADE;
    TIBStringField *IBQCliConsOcorrenciaSTATUS;
    TIBStringField *IBQCliConsOcorrenciaDESTATUS;
    TIBStringField *IBQCliConsOcorrenciaLOCAL;
    TIBStringField *IBQCliConsOcorrenciaRESUMO;
    TIBStringField *IBQCliConsOcorrenciaOPERADORABERTURA;
    TIBStringField *IBQCliConsOcorrenciaOPERADORENCERRAMENTO;
    TIBStringField *IBQCliConsOcorrenciaAGENTE;
    TIBBCDField *IBQCliConsOcorrenciaKMTOTALPERCORRIDO;
    TIBStringField *IBQCliConsOrdemServicoSITUACAO;
    TIntegerField *IBQCliConsOrdemServicoCDORDEMSERVICO;
    TIntegerField *IBQCliConsOrdemServicoCDCLIENTE;
    TIBStringField *IBQCliConsOrdemServicoNMCLIENTE;
    TDateTimeField *IBQCliConsOrdemServicoDATACADASTRO;
    TIBStringField *IBQCliConsOrdemServicoDEORDEMSERVICO;
    TIntegerField *IBQCliConsOrdemServicoEQUIPAMENTO;
    TStringField *CDSCliConsOrdemServicoSITUACAO;
    TIntegerField *CDSCliConsOrdemServicoCDORDEMSERVICO;
    TIntegerField *CDSCliConsOrdemServicoCDCLIENTE;
    TStringField *CDSCliConsOrdemServicoNMCLIENTE;
    TDateTimeField *CDSCliConsOrdemServicoDATACADASTRO;
    TStringField *CDSCliConsOrdemServicoDEORDEMSERVICO;
    TIntegerField *CDSCliConsOrdemServicoEQUIPAMENTO;
    TDataSource *DSMasterCliConsArmeDesarme;
    TDataSetField *CDSIdentificaZeroIBQCliConsArmeDesarme;
    TDataSetField *CDSIdentificaZeroIBQCliConsOrdemServico;
    TDateTimeField *IBQCliConsArmeDesarmeDATAEVENTO;
    TIntegerField *IBQCliConsArmeDesarmeCTX;
    TIntegerField *IBQCliConsArmeDesarmePORTACOM;
    TIntegerField *IBQCliConsArmeDesarmeEQUIPAMENTO;
    TIBStringField *IBQCliConsArmeDesarmeSTATUS;
    TIBStringField *IBQCliConsArmeDesarmeDESTATUS;
    TIntegerField *IBQCliConsArmeDesarmeCDCLIENTE;
    TIBStringField *IBQCliConsArmeDesarmeNMCLIENTE;
    TIBStringField *IBQCliConsArmeDesarmeENDERECO;
    TIBStringField *IBQCliConsArmeDesarmeCIDADE;
    TDataSource *DSMasterCliConsOcorrencia;
    TDataSetField *CDSIdentificaZeroIBQCliConsOcorrencia;
    TDataSource *DSMasterCliConsLogEvento;
    TDateTimeField *IBQCliConsLogEventoDATAEVENTO;
    TIntegerField *IBQCliConsLogEventoCTX;
    TIntegerField *IBQCliConsLogEventoPORTACOM;
    TIntegerField *IBQCliConsLogEventoEQUIPAMENTO;
    TIBStringField *IBQCliConsLogEventoSTATUS;
    TIBStringField *IBQCliConsLogEventoDESTATUS;
    TIntegerField *IBQCliConsLogEventoCDCLIENTE;
    TIBStringField *IBQCliConsLogEventoNMCLIENTE;
    TIBStringField *IBQCliConsLogEventoENDERECO;
    TIBStringField *IBQCliConsLogEventoCIDADE;
    TDataSetField *CDSIdentificaZeroIBQCliConsLogEvento;
    TDataSetField *CDSIdentificaIBQCliConsLogEvento;
    TDataSetField *CDSIdentificaIBQCliConsOcorrencia;
    TDataSetField *CDSIdentificaIBQCliConsArmeDesarme;
    TDataSetField *CDSIdentificaIBQCliConsOrdemServico;
    TDateTimeField *CDSCliConsLogEventoDATAEVENTO;
    TIntegerField *CDSCliConsLogEventoCTX;
    TIntegerField *CDSCliConsLogEventoPORTACOM;
    TIntegerField *CDSCliConsLogEventoEQUIPAMENTO;
    TStringField *CDSCliConsLogEventoSTATUS;
    TStringField *CDSCliConsLogEventoDESTATUS;
    TIntegerField *CDSCliConsLogEventoCDCLIENTE;
    TStringField *CDSCliConsLogEventoNMCLIENTE;
    TStringField *CDSCliConsLogEventoENDERECO;
    TStringField *CDSCliConsLogEventoCIDADE;
    TIntegerField *IBQIdentificaTOTAL_ATIVA;
    TIntegerField *IBQIdentificaTOTAL_PENDENTE;
    TIntegerField *IBQIdentificaTOTAL_REALIZADO;
    TIntegerField *CDSIdentificaTOTAL_ATIVA;
    TIntegerField *CDSIdentificaTOTAL_PENDENTE;
    TIntegerField *CDSIdentificaTOTAL_REALIZADO;
    TStringField *CDSIdentificaOBSERVACAO;
    TIntegerField *IBQSetorCurtoTOTAL_ATIVA;
    TIntegerField *IBQSetorCurtoTOTAL_PENDENTE;
    TIntegerField *IBQSetorCurtoTOTAL_REALIZADO;
    TIntegerField *CDSSetorCurtoTOTAL_ATIVA;
    TIntegerField *CDSSetorCurtoTOTAL_PENDENTE;
    TIntegerField *CDSSetorCurtoTOTAL_REALIZADO;
    TDataSetField *CDSSetorCurtoIBQCliConsLogEvento;
    TDataSetField *CDSSetorCurtoIBQCliConsOcorrencia;
    TDataSetField *CDSSetorCurtoIBQCliConsArmeDesarme;
    TDataSetField *CDSSetorCurtoIBQCliConsOrdemServico;
    TStringField *CDSSetorCurtoOBSERVACAO;
    TIntegerField *CDSBateriaFracaTOTAL_ATIVA;
    TIntegerField *CDSBateriaFracaTOTAL_PENDENTE;
    TIntegerField *CDSBateriaFracaTOTAL_REALIZADO;
    TStringField *CDSBateriaFracaOBSERVACAO;
    TDataSetField *CDSBateriaFracaIBQCliConsLogEvento;
    TDataSetField *CDSBateriaFracaIBQCliConsOcorrencia;
    TDataSetField *CDSBateriaFracaIBQCliConsArmeDesarme;
    TDataSetField *CDSBateriaFracaIBQCliConsOrdemServico;
    TDataSetField *CDSSensorIRContPresoIBQCliConsLogEvento;
    TDataSetField *CDSSensorIRContPresoIBQCliConsOcorrencia;
    TDataSetField *CDSSensorIRContPresoIBQCliConsArmeDesarme;
    TDataSetField *CDSSensorIRContPresoIBQCliConsOrdemServico;
    TStringField *CDSSensorIRContPresoOBSERVACAO;
    TIntegerField *CDSSensorIRContPresoTOTAL_ATIVA;
    TIntegerField *CDSSensorIRContPresoTOTAL_PENDENTE;
    TIntegerField *CDSSensorIRContPresoTOTAL_REALIZADO;
    TIntegerField *CDSConsertoSistemaTOTAL;
    TIntegerField *CDSConsertoSistemaCDCLIENTE;
    TStringField *CDSConsertoSistemaNMCLIENTE;
    TIntegerField *CDSConsertoSistemaEQUIPAMENTO;
    TStringField *CDSConsertoSistemaDESUBTIPOOCORRENCIA;
    TIntegerField *CDSConsertoSistemaTOTAL_ATIVA;
    TIntegerField *CDSConsertoSistemaTOTAL_PENDENTE;
    TIntegerField *CDSConsertoSistemaTOTAL_REALIZADO;
    TDataSetField *CDSConsertoSistemaIBQCliConsLogEvento;
    TDataSetField *CDSConsertoSistemaIBQCliConsOcorrencia;
    TDataSetField *CDSConsertoSistemaIBQCliConsArmeDesarme;
    TDataSetField *CDSConsertoSistemaIBQCliConsOrdemServico;
    TStringField *CDSConsertoSistemaOBSERVACAO;
    TIBTransaction *IBTRetiradaKit;
    TIBQuery *IBQRetiradaKit;
    TDataSetProvider *DSPRetiradaKit;
    TClientDataSet *CDSRetiradaKit;
    TDataSource *DSRetiradaKit;
    TStringField *CDSRetiradaKitOBSERVACAO;
    TDataSetField *CDSRetiradaKitIBQCliConsLogEvento;
    TDataSetField *CDSRetiradaKitIBQCliConsOcorrencia;
    TDataSetField *CDSRetiradaKitIBQCliConsArmeDesarme;
    TDataSetField *CDSRetiradaKitIBQCliConsOrdemServico;
    TIBTransaction *IBTCanalRFAberto;
    TIBQuery *IBQCanalRFAberto;
    TDataSetProvider *DSPCanalRFAberto;
    TClientDataSet *CDSCanalRFAberto;
    TDataSource *DSCanalRFAberto;
    TStringField *CDSCanalRFAbertoOBSERVACAO;
    TDataSetField *CDSCanalRFAbertoIBQCliConsLogEvento;
    TDataSetField *CDSCanalRFAbertoIBQCliConsOcorrencia;
    TDataSetField *CDSCanalRFAbertoIBQCliConsArmeDesarme;
    TDataSetField *CDSCanalRFAbertoIBQCliConsOrdemServico;
    TIBTransaction *IBTMauContato;
    TIBQuery *IBQMauContato;
    TDataSetProvider *DSPMauContato;
    TClientDataSet *CDSMauContato;
    TDataSource *DSMauContato;
    TStringField *CDSMauContatoOBSERVACAO;
    TDataSetField *CDSMauContatoIBQCliConsLogEvento;
    TDataSetField *CDSMauContatoIBQCliConsOcorrencia;
    TDataSetField *CDSMauContatoIBQCliConsArmeDesarme;
    TDataSetField *CDSMauContatoIBQCliConsOrdemServico;
    TIntegerField *CDSRetiradaKitTOTAL;
    TIntegerField *CDSRetiradaKitCDCLIENTE;
    TStringField *CDSRetiradaKitNMCLIENTE;
    TIntegerField *CDSRetiradaKitEQUIPAMENTO;
    TStringField *CDSRetiradaKitDESUBTIPOOCORRENCIA;
    TIntegerField *CDSRetiradaKitTOTAL_ATIVA;
    TIntegerField *CDSRetiradaKitTOTAL_PENDENTE;
    TIntegerField *CDSRetiradaKitTOTAL_REALIZADO;
    TIntegerField *CDSCanalRFAbertoTOTAL;
    TIntegerField *CDSCanalRFAbertoCDCLIENTE;
    TStringField *CDSCanalRFAbertoNMCLIENTE;
    TIntegerField *CDSCanalRFAbertoEQUIPAMENTO;
    TStringField *CDSCanalRFAbertoDESUBTIPOOCORRENCIA;
    TIntegerField *CDSCanalRFAbertoTOTAL_ATIVA;
    TIntegerField *CDSCanalRFAbertoTOTAL_PENDENTE;
    TIntegerField *CDSCanalRFAbertoTOTAL_REALIZADO;
    TIntegerField *CDSMauContatoTOTAL;
    TIntegerField *CDSMauContatoCDCLIENTE;
    TStringField *CDSMauContatoNMCLIENTE;
    TIntegerField *CDSMauContatoEQUIPAMENTO;
    TStringField *CDSMauContatoDESUBTIPOOCORRENCIA;
    TIntegerField *CDSMauContatoTOTAL_ATIVA;
    TIntegerField *CDSMauContatoTOTAL_PENDENTE;
    TIntegerField *CDSMauContatoTOTAL_REALIZADO;
    TIBTransaction *IBTSemEnergia;
    TIBQuery *IBQSemEnergia;
    TDataSetProvider *DSPSemEnergia;
    TClientDataSet *CDSSemEnergia;
    TDataSource *DSSemEnergia;
    TIntegerField *IBQSemEnergiaTOTAL;
    TIntegerField *IBQSemEnergiaCDCLIENTE;
    TIBStringField *IBQSemEnergiaNMCLIENTE;
    TIntegerField *IBQSemEnergiaEQUIPAMENTO;
    TIBStringField *IBQSemEnergiaDESUBTIPOOCORRENCIA;
    TIntegerField *IBQSemEnergiaTOTAL_ATIVA;
    TIntegerField *IBQSemEnergiaTOTAL_PENDENTE;
    TIntegerField *IBQSemEnergiaTOTAL_REALIZADO;
    TIntegerField *IBQMauContatoTOTAL;
    TIntegerField *IBQMauContatoCDCLIENTE;
    TIBStringField *IBQMauContatoNMCLIENTE;
    TIntegerField *IBQMauContatoEQUIPAMENTO;
    TIBStringField *IBQMauContatoDESUBTIPOOCORRENCIA;
    TIntegerField *IBQMauContatoTOTAL_ATIVA;
    TIntegerField *IBQMauContatoTOTAL_PENDENTE;
    TIntegerField *IBQMauContatoTOTAL_REALIZADO;
    TIntegerField *IBQCanalRFAbertoTOTAL;
    TIntegerField *IBQCanalRFAbertoCDCLIENTE;
    TIBStringField *IBQCanalRFAbertoNMCLIENTE;
    TIntegerField *IBQCanalRFAbertoEQUIPAMENTO;
    TIBStringField *IBQCanalRFAbertoDESUBTIPOOCORRENCIA;
    TIntegerField *IBQCanalRFAbertoTOTAL_ATIVA;
    TIntegerField *IBQCanalRFAbertoTOTAL_PENDENTE;
    TIntegerField *IBQCanalRFAbertoTOTAL_REALIZADO;
    TIntegerField *IBQRetiradaKitTOTAL;
    TIntegerField *IBQRetiradaKitCDCLIENTE;
    TIBStringField *IBQRetiradaKitNMCLIENTE;
    TIntegerField *IBQRetiradaKitEQUIPAMENTO;
    TIBStringField *IBQRetiradaKitDESUBTIPOOCORRENCIA;
    TIntegerField *IBQRetiradaKitTOTAL_ATIVA;
    TIntegerField *IBQRetiradaKitTOTAL_PENDENTE;
    TIntegerField *IBQRetiradaKitTOTAL_REALIZADO;
    TIntegerField *IBQConsertoSistemaTOTAL;
    TIntegerField *IBQConsertoSistemaCDCLIENTE;
    TIBStringField *IBQConsertoSistemaNMCLIENTE;
    TIntegerField *IBQConsertoSistemaEQUIPAMENTO;
    TIBStringField *IBQConsertoSistemaDESUBTIPOOCORRENCIA;
    TIntegerField *IBQConsertoSistemaTOTAL_ATIVA;
    TIntegerField *IBQConsertoSistemaTOTAL_PENDENTE;
    TIntegerField *IBQConsertoSistemaTOTAL_REALIZADO;
    TIntegerField *IBQSensorIRContPresoTOTAL;
    TIntegerField *IBQSensorIRContPresoCDCLIENTE;
    TIBStringField *IBQSensorIRContPresoNMCLIENTE;
    TIntegerField *IBQSensorIRContPresoEQUIPAMENTO;
    TIBStringField *IBQSensorIRContPresoDESUBTIPOOCORRENCIA;
    TIntegerField *IBQSensorIRContPresoTOTAL_ATIVA;
    TIntegerField *IBQSensorIRContPresoTOTAL_PENDENTE;
    TIntegerField *IBQSensorIRContPresoTOTAL_REALIZADO;
    TIntegerField *IBQBateriaFracaTOTAL;
    TIntegerField *IBQBateriaFracaCDCLIENTE;
    TIBStringField *IBQBateriaFracaNMCLIENTE;
    TIntegerField *IBQBateriaFracaEQUIPAMENTO;
    TIBStringField *IBQBateriaFracaDESUBTIPOOCORRENCIA;
    TIntegerField *IBQBateriaFracaTOTAL_ATIVA;
    TIntegerField *IBQBateriaFracaTOTAL_PENDENTE;
    TIntegerField *IBQBateriaFracaTOTAL_REALIZADO;
    TIntegerField *CDSSemEnergiaTOTAL;
    TIntegerField *CDSSemEnergiaCDCLIENTE;
    TStringField *CDSSemEnergiaNMCLIENTE;
    TIntegerField *CDSSemEnergiaEQUIPAMENTO;
    TStringField *CDSSemEnergiaDESUBTIPOOCORRENCIA;
    TIntegerField *CDSSemEnergiaTOTAL_ATIVA;
    TIntegerField *CDSSemEnergiaTOTAL_PENDENTE;
    TIntegerField *CDSSemEnergiaTOTAL_REALIZADO;
    TDataSetField *CDSSemEnergiaIBQCliConsLogEvento;
    TDataSetField *CDSSemEnergiaIBQCliConsOcorrencia;
    TDataSetField *CDSSemEnergiaIBQCliConsArmeDesarme;
    TDataSetField *CDSSemEnergiaIBQCliConsOrdemServico;
    TStringField *CDSSemEnergiaOBSERVACAO;
    TIBTransaction *IBTAgenteLocal;
    TIBQuery *IBQAgenteLocal;
    TDataSetProvider *DSPAgenteLocal;
    TClientDataSet *CDSAgenteLocal;
    TDataSource *DSAgenteLocal;
    TIntegerField *CDSAgenteLocalTOTAL;
    TIntegerField *CDSAgenteLocalCDCLIENTE;
    TStringField *CDSAgenteLocalNMCLIENTE;
    TIntegerField *CDSAgenteLocalEQUIPAMENTO;
    TStringField *CDSAgenteLocalDESUBTIPOOCORRENCIA;
    TIntegerField *CDSAgenteLocalTOTAL_ATIVA;
    TIntegerField *CDSAgenteLocalTOTAL_PENDENTE;
    TIntegerField *CDSAgenteLocalTOTAL_REALIZADO;
    TDataSetField *CDSAgenteLocalIBQCliConsLogEvento;
    TDataSetField *CDSAgenteLocalIBQCliConsOcorrencia;
    TDataSetField *CDSAgenteLocalIBQCliConsArmeDesarme;
    TDataSetField *CDSAgenteLocalIBQCliConsOrdemServico;
    TStringField *CDSAgenteLocalOBSERVACAO;
    TIBTransaction *IBTPresencaAnimais;
    TIBQuery *IBQPresencaAnimais;
    TDataSetProvider *DSPPresencaAnimais;
    TClientDataSet *CDSPresencaAnimais;
    TDataSource *DSPresencaAnimais;
    TIntegerField *IBQAgenteLocalTOTAL;
    TIntegerField *IBQAgenteLocalCDCLIENTE;
    TIBStringField *IBQAgenteLocalNMCLIENTE;
    TIntegerField *IBQAgenteLocalEQUIPAMENTO;
    TIBStringField *IBQAgenteLocalDESUBTIPOOCORRENCIA;
    TIntegerField *IBQAgenteLocalTOTAL_ATIVA;
    TIntegerField *IBQAgenteLocalTOTAL_PENDENTE;
    TIntegerField *IBQAgenteLocalTOTAL_REALIZADO;
    TIntegerField *IBQPresencaAnimaisTOTAL;
    TIntegerField *IBQPresencaAnimaisCDCLIENTE;
    TIBStringField *IBQPresencaAnimaisNMCLIENTE;
    TIntegerField *IBQPresencaAnimaisEQUIPAMENTO;
    TIBStringField *IBQPresencaAnimaisDESUBTIPOOCORRENCIA;
    TIntegerField *IBQPresencaAnimaisTOTAL_ATIVA;
    TIntegerField *IBQPresencaAnimaisTOTAL_PENDENTE;
    TIntegerField *IBQPresencaAnimaisTOTAL_REALIZADO;
    TIntegerField *CDSPresencaAnimaisTOTAL;
    TIntegerField *CDSPresencaAnimaisCDCLIENTE;
    TStringField *CDSPresencaAnimaisNMCLIENTE;
    TIntegerField *CDSPresencaAnimaisEQUIPAMENTO;
    TStringField *CDSPresencaAnimaisDESUBTIPOOCORRENCIA;
    TIntegerField *CDSPresencaAnimaisTOTAL_ATIVA;
    TIntegerField *CDSPresencaAnimaisTOTAL_PENDENTE;
    TIntegerField *CDSPresencaAnimaisTOTAL_REALIZADO;
    TDataSetField *CDSPresencaAnimaisIBQCliConsLogEvento;
    TDataSetField *CDSPresencaAnimaisIBQCliConsOcorrencia;
    TDataSetField *CDSPresencaAnimaisIBQCliConsArmeDesarme;
    TDataSetField *CDSPresencaAnimaisIBQCliConsOrdemServico;
    TStringField *CDSPresencaAnimaisOBSERVACAO;
    TIBTransaction *IBTAlarmeAcidental;
    TIBQuery *IBQAlarmeAcidental;
    TDataSetProvider *DSPAlarmeAcidental;
    TClientDataSet *CDSAlarmeAcidental;
    TDataSource *DSAlarmeAcidental;
    TIntegerField *IBQAlarmeAcidentalTOTAL;
    TIntegerField *IBQAlarmeAcidentalCDCLIENTE;
    TIBStringField *IBQAlarmeAcidentalNMCLIENTE;
    TIntegerField *IBQAlarmeAcidentalEQUIPAMENTO;
    TIBStringField *IBQAlarmeAcidentalDESUBTIPOOCORRENCIA;
    TIntegerField *IBQAlarmeAcidentalTOTAL_ATIVA;
    TIntegerField *IBQAlarmeAcidentalTOTAL_PENDENTE;
    TIntegerField *IBQAlarmeAcidentalTOTAL_REALIZADO;
    TIntegerField *CDSAlarmeAcidentalTOTAL;
    TIntegerField *CDSAlarmeAcidentalCDCLIENTE;
    TStringField *CDSAlarmeAcidentalNMCLIENTE;
    TIntegerField *CDSAlarmeAcidentalEQUIPAMENTO;
    TStringField *CDSAlarmeAcidentalDESUBTIPOOCORRENCIA;
    TIntegerField *CDSAlarmeAcidentalTOTAL_ATIVA;
    TIntegerField *CDSAlarmeAcidentalTOTAL_PENDENTE;
    TIntegerField *CDSAlarmeAcidentalTOTAL_REALIZADO;
    TStringField *CDSAlarmeAcidentalOBSERVACAO;
    TIntegerField *CDSCliConsOcorrenciaCDOCORRENCIA;
    TDateTimeField *CDSCliConsOcorrenciaDATAEVENTO;
    TIntegerField *CDSCliConsOcorrenciaCTX;
    TIntegerField *CDSCliConsOcorrenciaPORTACOM;
    TIntegerField *CDSCliConsOcorrenciaEQUIPAMENTO;
    TIntegerField *CDSCliConsOcorrenciaCDCLIENTE;
    TStringField *CDSCliConsOcorrenciaNMCLIENTE;
    TStringField *CDSCliConsOcorrenciaENDERECO;
    TStringField *CDSCliConsOcorrenciaCIDADE;
    TStringField *CDSCliConsOcorrenciaSTATUS;
    TStringField *CDSCliConsOcorrenciaDESTATUS;
    TStringField *CDSCliConsOcorrenciaLOCAL;
    TStringField *CDSCliConsOcorrenciaRESUMO;
    TStringField *CDSCliConsOcorrenciaOPERADORABERTURA;
    TStringField *CDSCliConsOcorrenciaOPERADORENCERRAMENTO;
    TStringField *CDSCliConsOcorrenciaAGENTE;
    TBCDField *CDSCliConsOcorrenciaKMTOTALPERCORRIDO;
    TIBTransaction *IBTSuspeitoLocal;
    TIBQuery *IBQSuspeitoLocal;
    TDataSetProvider *DSPSuspeitoLocal;
    TClientDataSet *CDSSuspeitoLocal;
    TDataSource *DSSuspeitoLocal;
    TIntegerField *IBQSuspeitoLocalTOTAL;
    TIntegerField *IBQSuspeitoLocalCDCLIENTE;
    TIBStringField *IBQSuspeitoLocalNMCLIENTE;
    TIntegerField *IBQSuspeitoLocalEQUIPAMENTO;
    TIBStringField *IBQSuspeitoLocalDESUBTIPOOCORRENCIA;
    TIntegerField *IBQSuspeitoLocalTOTAL_ATIVA;
    TIntegerField *IBQSuspeitoLocalTOTAL_PENDENTE;
    TIntegerField *IBQSuspeitoLocalTOTAL_REALIZADO;
    TIntegerField *CDSSuspeitoLocalTOTAL;
    TIntegerField *CDSSuspeitoLocalCDCLIENTE;
    TStringField *CDSSuspeitoLocalNMCLIENTE;
    TIntegerField *CDSSuspeitoLocalEQUIPAMENTO;
    TStringField *CDSSuspeitoLocalDESUBTIPOOCORRENCIA;
    TIntegerField *CDSSuspeitoLocalTOTAL_ATIVA;
    TIntegerField *CDSSuspeitoLocalTOTAL_PENDENTE;
    TIntegerField *CDSSuspeitoLocalTOTAL_REALIZADO;
    TStringField *CDSSuspeitoLocalOBSERVACAO;
    TDataSetField *CDSSuspeitoLocalIBQCliConsLogEvento;
    TDataSetField *CDSSuspeitoLocalIBQCliConsOcorrencia;
    TDataSetField *CDSSuspeitoLocalIBQCliConsArmeDesarme;
    TDataSetField *CDSSuspeitoLocalIBQCliConsOrdemServico;
    TDataSetField *CDSAlarmeAcidentalIBQCliConsLogEvento;
    TDataSetField *CDSAlarmeAcidentalIBQCliConsOcorrencia;
    TDataSetField *CDSAlarmeAcidentalIBQCliConsArmeDesarme;
    TDataSetField *CDSAlarmeAcidentalIBQCliConsOrdemServico;
    TIBTransaction *IBTSinalArrombamento;
    TIBQuery *IBQSinalArrombamento;
    TIntegerField *IntegerField1;
    TIntegerField *IntegerField2;
    TIBStringField *IBStringField1;
    TIntegerField *IntegerField3;
    TIBStringField *IBStringField2;
    TIntegerField *IntegerField5;
    TIntegerField *IntegerField7;
    TIntegerField *IntegerField8;
    TDataSetProvider *DSPSinalArrombamento;
    TDataSource *DSSinalArrombamento;
    TClientDataSet *CDSSinalArrombamento;
    TIntegerField *CDSSinalArrombamentoTOTAL;
    TIntegerField *CDSSinalArrombamentoCDCLIENTE;
    TStringField *CDSSinalArrombamentoNMCLIENTE;
    TIntegerField *CDSSinalArrombamentoEQUIPAMENTO;
    TStringField *CDSSinalArrombamentoDESUBTIPOOCORRENCIA;
    TIntegerField *CDSSinalArrombamentoTOTAL_ATIVA;
    TIntegerField *CDSSinalArrombamentoTOTAL_PENDENTE;
    TIntegerField *CDSSinalArrombamentoTOTAL_REALIZADO;
    TDataSetField *CDSSinalArrombamentoIBQCliConsLogEvento;
    TDataSetField *CDSSinalArrombamentoIBQCliConsOcorrencia;
    TDataSetField *CDSSinalArrombamentoIBQCliConsArmeDesarme;
    TDataSetField *CDSSinalArrombamentoIBQCliConsOrdemServico;
    TStringField *CDSSinalArrombamentoOBSERVACAO;
    TIBTransaction *IBTJanelaMalFechada;
    TIBQuery *IBQJanelaMalFechada;
    TIntegerField *IntegerField9;
    TIntegerField *IntegerField10;
    TIBStringField *IBStringField3;
    TIntegerField *IntegerField11;
    TIBStringField *IBStringField4;
    TIntegerField *IntegerField12;
    TIntegerField *IntegerField13;
    TIntegerField *IntegerField14;
    TDataSetProvider *DSPJanelaMalFechada;
    TClientDataSet *CDSJanelaMalFechada;
    TDataSource *DSJanelaMalFechada;
    TIntegerField *CDSJanelaMalFechadaTOTAL;
    TIntegerField *CDSJanelaMalFechadaCDCLIENTE;
    TStringField *CDSJanelaMalFechadaNMCLIENTE;
    TIntegerField *CDSJanelaMalFechadaEQUIPAMENTO;
    TStringField *CDSJanelaMalFechadaDESUBTIPOOCORRENCIA;
    TIntegerField *CDSJanelaMalFechadaTOTAL_ATIVA;
    TIntegerField *CDSJanelaMalFechadaTOTAL_PENDENTE;
    TIntegerField *CDSJanelaMalFechadaTOTAL_REALIZADO;
    TDataSetField *CDSJanelaMalFechadaIBQCliConsLogEvento;
    TDataSetField *CDSJanelaMalFechadaIBQCliConsOcorrencia;
    TDataSetField *CDSJanelaMalFechadaIBQCliConsArmeDesarme;
    TDataSetField *CDSJanelaMalFechadaIBQCliConsOrdemServico;
    TStringField *CDSJanelaMalFechadaOBSERVACAO;
    TIBTransaction *IBTSinalIndesejado;
    TIBQuery *IBQSinalIndesejado;
    TDataSetProvider *DSPSinalIndesejado;
    TClientDataSet *CDSSinalIndesejado;
    TDataSource *DSSinalIndesejado;
    TIntegerField *IBQSinalIndesejadoTOTAL;
    TIntegerField *IBQSinalIndesejadoCDCLIENTE;
    TIBStringField *IBQSinalIndesejadoNMCLIENTE;
    TIntegerField *IBQSinalIndesejadoEQUIPAMENTO;
    TIBStringField *IBQSinalIndesejadoDESUBTIPOOCORRENCIA;
    TIntegerField *IBQSinalIndesejadoTOTAL_ATIVA;
    TIntegerField *IBQSinalIndesejadoTOTAL_PENDENTE;
    TIntegerField *IBQSinalIndesejadoTOTAL_REALIZADO;
    TIntegerField *CDSSinalIndesejadoTOTAL;
    TIntegerField *CDSSinalIndesejadoCDCLIENTE;
    TStringField *CDSSinalIndesejadoNMCLIENTE;
    TIntegerField *CDSSinalIndesejadoEQUIPAMENTO;
    TStringField *CDSSinalIndesejadoDESUBTIPOOCORRENCIA;
    TIntegerField *CDSSinalIndesejadoTOTAL_ATIVA;
    TIntegerField *CDSSinalIndesejadoTOTAL_PENDENTE;
    TIntegerField *CDSSinalIndesejadoTOTAL_REALIZADO;
    TDataSetField *CDSSinalIndesejadoIBQCliConsLogEvento;
    TDataSetField *CDSSinalIndesejadoIBQCliConsOcorrencia;
    TDataSetField *CDSSinalIndesejadoIBQCliConsArmeDesarme;
    TDataSetField *CDSSinalIndesejadoIBQCliConsOrdemServico;
    TStringField *CDSSinalIndesejadoOBSERVACAO;
    TTreeView *TVEventosAnalisados;
    TSplitter *Splitter3;
    void __fastcall MnSairClick(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall MnCadContratoClick(TObject *Sender);
    void __fastcall MnCadClienteClick(TObject *Sender);
    void __fastcall MnConsClientesClick(TObject *Sender);
    void __fastcall MnCadProcedimentoClick(TObject *Sender);
    void __fastcall MnFiliaisClick(TObject *Sender);
    void __fastcall MnUsuariosClick(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall DBGOcorrenciasHistDblClick(TObject *Sender);
    void __fastcall BtnConsultarClick(TObject *Sender);
    void __fastcall TMRConsultaTimer(TObject *Sender);
    void __fastcall CkbAtualizarClick(TObject *Sender);
    void __fastcall MnCadMonitoramentoClick(TObject *Sender);
    void __fastcall TMRMonitoramentoTimer(TObject *Sender);
    void __fastcall IBEOcorrenciaEventAlert(TObject *Sender,
          AnsiString EventName, int EventCount, bool &CancelAlerts);
    void __fastcall MnMonitor1Click(TObject *Sender);
    void __fastcall MnMonitor2Click(TObject *Sender);
    void __fastcall MnMonitor3Click(TObject *Sender);
    void __fastcall MnMonitor4Click(TObject *Sender);
    void __fastcall MnMonitor5Click(TObject *Sender);
    void __fastcall MnMonitor6Click(TObject *Sender);
    void __fastcall MnMonitor7Click(TObject *Sender);
    void __fastcall MnMonitor8Click(TObject *Sender);
    void __fastcall MnMonitor9Click(TObject *Sender);
    void __fastcall MnMonitor10Click(TObject *Sender);
    void __fastcall MnMonitor11Click(TObject *Sender);
    void __fastcall MnMonitor12Click(TObject *Sender);
    void __fastcall MnMonitor13Click(TObject *Sender);
    void __fastcall MnMonitor14Click(TObject *Sender);
    void __fastcall MnMonitor15Click(TObject *Sender);
    void __fastcall MnMonitor16Click(TObject *Sender);
    void __fastcall BtnConsultarOCClick(TObject *Sender);
    void __fastcall DBGOcorrenciasDblClick(TObject *Sender);
    void __fastcall DSPConsFaltaComunicacaoGetTableName(TObject *Sender,
          TDataSet *DataSet, AnsiString &TableName);
    void __fastcall MnRelAtendimentoClick(TObject *Sender);
    void __fastcall MnCadastrarOSClick(TObject *Sender);
    void __fastcall MnConsultarOSClick(TObject *Sender);
    void __fastcall MnCadCodificadorClick(TObject *Sender);
    void __fastcall BtnImprimirOCClick(TObject *Sender);
    void __fastcall MnAbrirOcorrenciaClick(TObject *Sender);
    void __fastcall TVEventosAnalisadosClick(TObject *Sender);
    void __fastcall CDSIdentificaZeroCalcFields(TDataSet *DataSet);
    void __fastcall CDSIdentificaCalcFields(TDataSet *DataSet);
    void __fastcall DBGClientesManutencaoDrawColumnCell(TObject *Sender,
          const TRect &Rect, int DataCol, TColumn *Column,
          TGridDrawState State);
    void __fastcall DBGCliConsOrdensAbertasDblClick(TObject *Sender);
    void __fastcall BtnConsultarManutPreventivasClick(TObject *Sender);
    void __fastcall CDSSetorCurtoCalcFields(TDataSet *DataSet);
    void __fastcall CDSBateriaFracaCalcFields(TDataSet *DataSet);
    void __fastcall CDSSensorIRContPresoCalcFields(TDataSet *DataSet);
    void __fastcall CDSConsertoSistemaCalcFields(TDataSet *DataSet);
    void __fastcall CDSRetiradaKitCalcFields(TDataSet *DataSet);
    void __fastcall CDSCanalRFAbertoCalcFields(TDataSet *DataSet);
    void __fastcall CDSMauContatoCalcFields(TDataSet *DataSet);
    void __fastcall CDSSemEnergiaCalcFields(TDataSet *DataSet);
    void __fastcall CDSAgenteLocalCalcFields(TDataSet *DataSet);
    void __fastcall CDSPresencaAnimaisCalcFields(TDataSet *DataSet);
    void __fastcall CDSAlarmeAcidentalCalcFields(TDataSet *DataSet);
    void __fastcall CDSSuspeitoLocalCalcFields(TDataSet *DataSet);
    void __fastcall CDSSinalArrombamentoCalcFields(TDataSet *DataSet);
    void __fastcall CDSJanelaMalFechadaCalcFields(TDataSet *DataSet);
    void __fastcall DBGCliConsOcorrenciasDblClick(TObject *Sender);
    void __fastcall CDSSinalIndesejadoCalcFields(TDataSet *DataSet);
private:	// User declarations
    // Métodos
    HWND __fastcall CarregaMonitor(LPCTSTR program, LPCTSTR args);
    void __fastcall ConfiguraCriteriosEventosSQL();
    void __fastcall ConfiguraCriteriosOcorrenciasSQL();    
    bool __fastcall ValidaOcorrencia();

public:		// User declarations
    __fastcall TFHome(TComponent* Owner);
    void __fastcall AtualizarListaOcorrencias();
    bool __fastcall FormEstaAberto(AnsiString Name);
    TForm* OcorrenciaEmAtendimento(int iCdOcorrencia);
};

//---------------------------------------------------------------------------
extern PACKAGE TFHome *FHome;
//---------------------------------------------------------------------------

#ifndef AZSIM
#define AZSIM  extern
#else
#define AZSIM
#endif

#define NR_RETRANSMISSOES_CTX     2
#define ESPERA_RESPOSTA_CTX       200
#define PERIODO_TIMER             30
#define NR_MAX_MSG                1000
#define TAM_CAMINHO               30
#define TAM_BUFFER                1000

#define SetBit(a,b)               (a |=  (0x01<<(b)))
#define ClearBit(a,b)             (a &= ~(0x01<<(b)))
#define CheckBit(a,b)             ((a>>b) & 0x01)

AZSIM char acBuffer[TAM_BUFFER];

#endif
