CREATE OR ALTER PROCEDURE SP_CONS_LOGULTIMOESTADO (NUMDIAS INTEGER)
RETURNS (
	RCDCLIENTE INTEGER,
	RNMCLIENTE VARCHAR(256),
	RCDCODIFICADOR INTEGER,
	RDATAULTIMOEVENTO TIMESTAMP,
	RDESCEVENTO VARCHAR(256)
)
AS
DECLARE VARIABLE DATAULTIMOEVENTO TIMESTAMP;
DECLARE VARIABLE CDCLIENTE INTEGER;
BEGIN
    FOR SELECT MAX(LL.DATAULTIMOEVENTO), LL.CDCLIENTE
            FROM LOGULTIMOESTADO LL
                JOIN CLIENTE C ON C.CDCLIENTE = LL.CDCLIENTE
                JOIN CONTRATO CO ON CO.CDCLIENTE = LL.CDCLIENTE AND CO.INATIVO = 0
            WHERE
                LL.DATACADASTRO > DATEADD(-:NUMDIAS DAY TO CURRENT_DATE) AND
                LL.CDCLIENTE
                    NOT IN(
                        SELECT DISTINCT L.CDCLIENTE FROM LOGULTIMOESTADO L
                          WHERE L.DATACADASTRO > DATEADD(-:NUMDIAS DAY TO CURRENT_DATE)
                          AND L.IDENTIFICACAO IS NOT NULL
                    )
        GROUP BY LL.CDCLIENTE
        ORDER BY MAX(LL.DATAULTIMOEVENTO), LL.CDCLIENTE INTO :DATAULTIMOEVENTO, :CDCLIENTE
    DO
        FOR SELECT LL.CDCLIENTE, C.NMCLIENTE, CO.CDCODIFICADOR, LL.DATAULTIMOEVENTO, LL.ULTIMOEVENTO
            FROM LOGULTIMOESTADO LL
                    JOIN CLIENTE C ON C.CDCLIENTE = LL.CDCLIENTE
                    JOIN CONTRATO CO ON CO.CDCLIENTE = LL.CDCLIENTE AND CO.INATIVO = 0
                WHERE LL.CDCLIENTE = :CDCLIENTE AND LL.DATAULTIMOEVENTO = :DATAULTIMOEVENTO
            INTO :RCDCLIENTE, :RNMCLIENTE, :RCDCODIFICADOR, :RDATAULTIMOEVENTO, :RDESCEVENTO
        DO
            SUSPEND;
END