SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_CONS_LOGULTIMOESTADO (
    NUMDIAS INTEGER)
RETURNS (
    CDCLIENTE INTEGER,
    NMCLIENTE NOME_FANTASIA,
    CDCODIFICADOR INTEGER,
    DATAULTIMOEVENTO TIMESTAMP,
    ULTIMOEVENTO VARCHAR(256))
AS
DECLARE VARIABLE VDATAULTIMOEVENTO TIMESTAMP;
DECLARE VARIABLE VCDCLIENTE INTEGER;
BEGIN
    FOR SELECT MAX(LL.DATAULTIMOEVENTO) AS DATAULTIMOEVENTO, LL.CDCLIENTE 
        FROM LOGULTIMOESTADO LL 
        WHERE LL.DATACADASTRO > DATEADD(-180 DAY TO CURRENT_DATE) AND NOT EXISTS(
            SELECT DISTINCT L.CDCLIENTE 
            FROM LOGULTIMOESTADO L 
            WHERE L.DATACADASTRO > DATEADD(-:NUMDIAS DAY TO CURRENT_DATE) AND L.CDCLIENTE = LL.CDCLIENTE
            ORDER BY L.CDCLIENTE
        )
        GROUP BY LL.CDCLIENTE
        ORDER BY MAX(LL.DATAULTIMOEVENTO) INTO :VDATAULTIMOEVENTO, :VCDCLIENTE
    DO
        FOR SELECT LL.CDCLIENTE, C.NMCLIENTE, CO.CDCODIFICADOR, LL.DATAULTIMOEVENTO, LL.ULTIMOEVENTO
            FROM LOGULTIMOESTADO LL
                    JOIN CLIENTE C ON C.CDCLIENTE = LL.CDCLIENTE
                    JOIN CONTRATO CO ON CO.CDCLIENTE = LL.CDCLIENTE AND CO.INATIVO = 0
                WHERE LL.CDCLIENTE = :VCDCLIENTE AND LL.DATAULTIMOEVENTO = :VDATAULTIMOEVENTO
            INTO :CDCLIENTE, :NMCLIENTE, :CDCODIFICADOR, :DATAULTIMOEVENTO, :ULTIMOEVENTO
        DO
            SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON LOGULTIMOESTADO TO PROCEDURE SP_CONS_LOGULTIMOESTADO;
GRANT SELECT ON CLIENTE TO PROCEDURE SP_CONS_LOGULTIMOESTADO;
GRANT SELECT ON CONTRATO TO PROCEDURE SP_CONS_LOGULTIMOESTADO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE SP_CONS_LOGULTIMOESTADO TO SYSDBA;